sudo: true

language: bash

services:
  - docker

env:
  global:
    - DEBIAN_FRONTEND="noninteractive"
    - DOCKERHUB_LIVE="netbootxyz/iso-processor"
    - DOCKER_TAG="latest"

jobs:
  include:
    - stage: Build and Push
      if: (NOT (type IN (pull_request)))
      script:
        # Build Dev image
        - docker build --no-cache -f Dockerfile -t ${DOCKERHUB_LIVE}:${TRAVIS_COMMIT} .
        - docker tag ${DOCKERHUB_LIVE}:${TRAVIS_COMMIT} ${DOCKERHUB_LIVE}:${DOCKER_TAG}
        # Login to DockerHub
        - echo $DOCKERPASS | docker login -u $DOCKERUSER --password-stdin
        # Push all of the tags
        - docker push ${DOCKERHUB_LIVE}:${TRAVIS_COMMIT}
        - docker push ${DOCKERHUB_LIVE}:${DOCKER_TAG}
